sudo: false

matrix:
    include:
      - compiler: python-cpplint
        language: python
        install:
            - pip install cpplint
        script:
            - "cpplint --linelength=100 --extensions=cc,hh --filter=-legal,-runtime/int,-runtime/references src/*/*"
        cache:

      - compiler: gcc-4.9
        language: cpp
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
                    - libgtest-dev
        env:
            - COMPILERXX="g++-4.9"
            - COMPILERC="gcc-4.9"

      - compiler: gcc-5
        language: cpp
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
                    - libgtest-dev
        env:
            - COMPILERXX="g++-5"
            - COMPILERC="gcc-5"

      - compiler: clang-3.6
        language: cpp
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise-3.6
                packages:
                    - clang-3.6
                    - libgtest-dev
        env:
            - COMPILERXX="clang++-3.6"
            - COMPILERC="clang-3.6"

    ## disabled because of https://llvm.org/bugs/show_bug.cgi?id=22757, waiting for
    #   - compiler: clang-3.8
    #     language: cpp
    #     addons:
    #         apt:
    #             sources:
    #                 - ubuntu-toolchain-r-test
    #                 - llvm-toolchain-precise
    #             packages:
    #                 - clang-3.8
    #                 - libgtest-dev
    #     env:
    #         - COMPILERXX="clang++-3.8"
    #         - COMPILERC="clang-3.8"

cache:
    apt: true
    directories:
        - $HOME/gtest/

install:
  - export CXX=$COMPILERXX CC=$COMPILERC
  - $CXX --version
# - "if [ ! -f $HOME/gtest/libgtest.a ]; then .... ; fi
  - "mkdir -p $HOME/gtest && cd $HOME/gtest && cmake --target install -DCMAKE_INSTALL_PREFIX=$HOME/lib/ -Dgtest_disable_pthreads=ON /usr/src/gtest && cmake --build . && cd -"
  - rm -rf $HOME/gtest/CMakeFiles/Makefile.cmake #for cache
  - ls $HOME/gtest
  - export LIBRARY_PATH=$HOME/gtest/:$LIBRARY_PATH

script: make debug && make tests

