sudo: true
language: cpp
script: make && make tests
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_install:
  - "cd /usr/src/gtest && sudo rm -f Makefile; sudo cmake . -Dgtest_disable_pthreads=ON  && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libgtest-dev
